name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Gradle
      id: cachegradle
      continue-on-error: true
      uses: actions/cache@v1.0.3
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Cache Node
      id: cachenode
      continue-on-error: true
      uses: actions/cache@v1.0.3
      with:
        path: ~/build/js
        key: ${{ runner.os }}-js-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-js-
    - name: gradlew preconditions (temporary fix for the eap dependency problem)
      run: ./gradlew :jsProcessResources
    - name: gradlew build
      run: ./gradlew build
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: build/distributions
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
