name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache
      continue-on-error: true
      uses: actions/cache@v1.0.3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: gradlew build
      run: ./gradlew build
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
